---
deployment:
  tasks:
    - export DEPLOYPATH=/data0/aimyservice.com/public_html
    - /bin/cp -r aimyservice.com/. $DEPLOYPATH/aimyservicecom/
    - /bin/cp -r aaifactory.com/. $DEPLOYPATH/aaifactorycom/
    - /bin/cp -r aiagencyforautomation.com/. $DEPLOYPATH/aiagencyforautomationcom/
    - /bin/cp -r aibiogenius.com/. $DEPLOYPATH/aibiogeniuscom/
    - /bin/cp -r aicareerplanner.com/. $DEPLOYPATH/aicareerplannercom/
    - /bin/cp -r aiforbars.com/. $DEPLOYPATH/aiforbarscom/
    - /bin/cp -r aiforcasinos.com/. $DEPLOYPATH/aiforcasinoscom/
    - /bin/cp -r aiforlongevity.dev/. $DEPLOYPATH/aiforlongevitydev/
    - /bin/cp -r aiforrestaurants.com/. $DEPLOYPATH/aiforrestaurantscom/
    - /bin/cp -r aiintelligencefactory.com/. $DEPLOYPATH/aiintelligencefactorycom/
    - /bin/cp -r aijobscoach.com/. $DEPLOYPATH/aijobscoachcom/
    - /bin/cp -r ailunchclubs.com/. $DEPLOYPATH/ailunchclubscom/
    - /bin/cp -r aimusicmemories.com/. $DEPLOYPATH/aimusicmemoriescom/
    - /bin/cp -r aimyarchive.com/. $DEPLOYPATH/aimyarchivecom/
    - /bin/cp -r aimybio.com/. $DEPLOYPATH/aimybiocom/
    - /bin/cp -r aimygifting.com/. $DEPLOYPATH/aimygiftingcom/
    - /bin/cp -r aimyinterview.com/. $DEPLOYPATH/aimyinterviewcom/
    - /bin/cp -r aimyoffice.org/. $DEPLOYPATH/aimyofficeorg/
    - /bin/cp -r aimypractice.org/. $DEPLOYPATH/aimypracticeorg/
    - /bin/cp -r aimyservices.com/. $DEPLOYPATH/aimyservicescom/
    - /bin/cp -r aimyshopping.com/. $DEPLOYPATH/aimyshoppingcom/
    - /bin/cp -r aimysoundtrack.com/. $DEPLOYPATH/aimysoundtrackcom/
    - /bin/cp -r aisocietynews.com/. $DEPLOYPATH/aisocietynewscom/
    - /bin/cp -r aiwisdomfactory.com/. $DEPLOYPATH/aiwisdomfactorycom/
    - /bin/cp -r aiwizards.work/. $DEPLOYPATH/aiwizardswork/
    - /bin/cp -r allstaravatars.com/. $DEPLOYPATH/allstaravatarscom/
    - /bin/cp -r avastar.band/. $DEPLOYPATH/avastarband/
    - /bin/cp -r avatarallstars.com/. $DEPLOYPATH/avatarallstarscom/
    - /bin/cp -r creativeintelligencesystem.com/. $DEPLOYPATH/creativeintelligencesystemcom/
    - /bin/cp -r lifeisabeautifulthing.com/. $DEPLOYPATH/lifeisabeautifulthingcom/
    - /bin/cp -r repeatableintelligence.com/. $DEPLOYPATH/repeatableintelligencecom/
    - /bin/cp -r talktomeinheaven.com/. $DEPLOYPATH/talktomeinheavencom/
    - /bin/cp -r cheerssocial.com/. $DEPLOYPATH/cheerssocialcom/
    - /bin/cp -r cheerscentral.com/. $DEPLOYPATH/cheerscentralcom/
    - /bin/cp -r happyhoursocial.com/. $DEPLOYPATH/happyhoursocialcom/
    - /bin/cp -r nolagoats.com/. $DEPLOYPATH/nolagoatscom/
    - /bin/cp -r nolalunchclub.com/. $DEPLOYPATH/nolalunchclubcom/
    - /bin/cp -r tastetournola.com/. $DEPLOYPATH/tastetournolacom/
    - /bin/cp -r globaltix.app/. $DEPLOYPATH/globaltixapp/
    - /bin/cp -r ticketsdirect.app/. $DEPLOYPATH/ticketsdirectapp/
    - /bin/cp -r davefurano.com/. $DEPLOYPATH/davefuranocom/
    - /bin/cp -r dellfurano.com/. $DEPLOYPATH/dellfuranocom/
    - /bin/cp -r gratefuldave.com/. $DEPLOYPATH/gratefuldavecom/
    - /bin/cp -r kellyfurano.com/. $DEPLOYPATH/kellyfuranocom/
    - /bin/cp -r rememberingwinterland.com/. $DEPLOYPATH/rememberingwinterlandcom/
    - /bin/cp -r sandybrew.com/. $DEPLOYPATH/sandybrewcom/
    - /bin/cp -r sandyfurano.com/. $DEPLOYPATH/sandyfuranocom/
    - /bin/cp -r sandyspritz.com/. $DEPLOYPATH/sandyspritzcom/
