---
deployment:
  tasks:
    - export DEPLOYPATH=/data0/aimyservice.com/public_html
    - /bin/mkdir -p $DEPLOYPATH/aaifactorycom $DEPLOYPATH/aiagencyforautomationcom $DEPLOYPATH/aicareerplannercom $DEPLOYPATH/aiforbarscom $DEPLOYPATH/aiforcasinoscom
    - /bin/cp -rf aaifactory.com/. $DEPLOYPATH/aaifactorycom/ && /bin/cp -rf aiagencyforautomation.com/. $DEPLOYPATH/aiagencyforautomationcom/ && /bin/cp -rf aicareerplanner.com/. $DEPLOYPATH/aicareerplannercom/ && /bin/cp -rf aiforbars.com/. $DEPLOYPATH/aiforbarscom/ && /bin/cp -rf aiforcasinos.com/. $DEPLOYPATH/aiforcasinoscom/
